---
apiVersion: concourse.k8s.io/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: killswitch-integration
spec:
  exposed: false
  paused: true
  config:

    task_toolbox: &task_toolbox
      type: docker-image
      source:
        repository: ((concourse.task-toolbox-image))
        tag: ((concourse.task-toolbox-tag))

    jobs:

    - name: kill
      plan:
      - task: delete-resources
        timeout: 10m
        config:
          platform: linux
          image_resource: *task_toolbox
          params:
            KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
            KUBERNETES_TOKEN: ((namespace-deployer.token))
            NAMESPACE: ((namespace-deployer.namespace))
          run:
            path: /bin/bash
            args:
              - -euc
              - |
                echo "configuring kubectl"
                echo "${KUBERNETES_SERVICE_ACCOUNT}" | jq -r .["ca.crt"] > ca.crt
                kubectl config set-cluster self --server=https://kubernetes.default --certificate-authority=ca.crt
                kubectl config set-credentials deployer --token "${KUBERNETES_TOKEN}"
                kubectl config set-context deployer --user deployer --cluster self
                kubectl config use-context deployer

                kubectl -n "${NAMESPACE}" delete virtualservices,deployments --all
