kind: Redis
apiVersion: database.govsvc.uk/v1beta1
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis
spec:
  aws:
    nodeType: cache.t3.micro
    engineVersion: 5.0.6
    numCacheClusters: 2
    preferredMaintenanceWindow: sun:23:30-mon:01:30
  secret: {{ .Release.Name }}-redis-secret
