apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    timestamp: {{ .Release.Time }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: db
          image: govsvc/redis-and-stunnel
          command: ['sleep', '1000000']
          env:
            - name: STUNNEL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: ClusterPrimaryRedisHostname
            - name: STUNNEL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: ClusterPrimaryRedisPort
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: SecretAuthToken
