{
 "title": "eIDAS Proxy Node Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "eIDAS Responses (last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(verify_proxy_node_successful_responses_total{namespace=\"verify-proxy-node-prod\"}[24h])) by (release)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Errors pages (1h)",
   "type": "bargauge",
   "description": "Errors where the user could not be sent back to the eIDAS connector node, i.e. their journey ended in failure on a Verify error page.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(verify_proxy_node_failure_error_page{namespace=\"verify-proxy-node-prod\"}[1h])",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Error responses (1h)",
   "type": "bargauge",
   "description": "Errors where the user was sent back to the eIDAS connector node due to a failure to register or sign in.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "\nincrease(verify_proxy_node_failure_saml_error_responses_total{namespace=\"verify-proxy-node-prod\"}[1h])",
     "legendFormat": "{{release}}"
    }
   ]
  }
 ]
}