apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "verify-service-provider.name" . }}
    chart: {{ template "verify-service-provider.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "verify-service-provider.fullname" . }}
data:
  verify-service-provider.yaml: |-
{{ toYaml .Values.configFile | indent 4 }}