tap "cloudfoundry/tap"
tap "homebrew/cask"

brew "cf-cli"
brew "docker-compose"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "md5sha1sum"
brew "minikube"
brew "pre-commit"
brew "xmlsectool"
brew "yq"

cask "docker"
cask "virtualbox" # for virtualbox install you may have to go to system preferences > security and allow Oracle access at the bottom

