version: '3'

services:
  proxy-node-gateway:
    image: govukverify/proxy-node-gateway:latest
    build:
      context: .
      args:
        component: proxy-node-gateway
  proxy-node-translator:
    image: govukverify/proxy-node-translator:latest
    build:
      context: .
      dockerfile: proxy-node-translator/Dockerfile
  stub-connector:
    image: govukverify/stub-connector:latest
    build:
      context: .
      args:
        component: stub-connector
  eidas-saml-parser:
    image: govukverify/eidas-saml-parser:latest
    build:
      context: .
      args:
        component: eidas-saml-parser
