ruby '2.6.5'

source 'https://rubygems.org'

gem 'capybara', '>= 3.32.2'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'geckodriver-helper'
gem 'webdrivers', '~> 4.0'
gem 'capybara-screenshot', '>= 1.0.24'
