package uk.gov.ida.notification.shared.logging;

public enum ProxyNodeMDCKey {
    HUB_REQUEST_ID,
    HUB_URL,
    EIDAS_REQUEST_ID,
    EIDAS_ISSUE_INSTANT,
    EIDAS_ISSUER,
    EIDAS_DESTINATION,
    CONNECTOR_PUBLIC_ENC_CERT_SUFFIX,
    SIGNING_PROVIDER,
    EIDAS_LOA,
    SESSION_ID,
    REFERER,
    RESOURCE_PATH,
    RESPONSE_STATUS,
    EGRESS_LOCATION,
    EGRESS_MEDIA_TYPE,
    INGRESS_MEDIA_TYPE,
    PROXY_NODE_JOURNEY_ID,
    HSM_KEY_HANDLE
}
