package uk.gov.ida.notification.shared;

public enum ProxyNodeMDCKey {
    LOG_LOCATION,
    HUB_REQUEST_ID,
    HUB_URL,
    EIDAS_REQUEST_ID,
    EIDAS_ISSUE_INSTANT,
    EIDAS_ISSUER,
    EIDAS_DESTINATION,
    CONNECTOR_PUBLIC_ENC_CERT_SUFFIX,
    SIGNING_PROVIDER,
    EIDAS_LOA,
    REQUEST_ID,
    EXCEPTION_CAUSE,
    EXCEPTION_STACKTRACE,
    EXCEPTION_MESSAGE,
    SESSION_ID
}