package uk.gov.ida.notification.shared;

public enum ProxyNodeMDCKey {
    LOG_LOCATION,
    HUB_REQUEST_ID,
    HUB_URL,
    EIDAS_REQUEST_ID,
    EIDAS_ISSUE_INSTANT,
    EIDAS_ISSUER,
    EIDAS_DESTINATION,
    CONNECTOR_PUBLIC_ENC_CERT_SUFFIX,
    SIGNING_PROVIDER
}