package uk.gov.ida.notification.shared;

public enum ProxyNodeMDCKey {
    LOG_LOCATION,
    HUB_REQUEST_ID,
    HUB_URL,
    EIDAS_REQUEST_ID,
    EIDAS_ISSUE_INSTANT,
    EIDAS_ISSUER,
    EIDAS_DESTINATION,
    CONNECTOR_PUBLIC_ENC_CERT_SUFFIX,
    SIGNING_PROVIDER,
    EIDAS_LOA,
    EXCEPTION_CAUSE,
    EXCEPTION_STACKTRACE,
    EXCEPTION_MESSAGE,
    SESSION_ID,
    REFERER,
    RESOURCE_PATH,
    RESPONSE_STATUS,
    EGRESS_LOCATION,
    EGRESS_MEDIA_TYPE,
    INGRESS_MEDIA_TYPE,
    PROXY_NODE_JOURNEY_ID
}
