{
 "title": "Proxy Node Prod Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "TimePeriod",
    "label": "Time Period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Responses avg over $TimePeriod",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (issuer)(increase(verify_proxy_node_successful_responses_total{release=\"production\"}[$TimePeriod]))",
     "legendFormat": "{{issuer}}"
    }
   ]
  },
  {
   "title": "Successful Req Rate over $TimePeriod",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(verify_proxy_node_successful_requests_total{release=\"production\"}[$TimePeriod]))\n\n/\n\nsum (rate(verify_proxy_node_requests_total{release=\"production\"}[$TimePeriod]))"
    }
   ]
  },
  {
   "title": "Successful Resp Rate over $TimePeriod",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(verify_proxy_node_successful_responses_total{release=\"production\"}[$TimePeriod]))\n\n/\n\nsum (rate(verify_proxy_node_responses_total{release=\"production\"}[$TimePeriod]))"
    }
   ]
  },
  {
   "title": "HSM Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Region": "eu-west-2" },
     "metricName": "HsmKeysSessionOccupied",
     "namespace": "AWS/CloudHSM",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Requests avg over $TimePeriod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (issuer)(increase(verify_proxy_node_successful_requests_total{release=\"production\"}[$TimePeriod]))",
     "legendFormat": "{{issuer}}"
    }
   ]
  }
 ]
}