apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-redis
  labels:
    app.kubernetes.io/name: gateway-redis
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: gateway-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
