apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-translator
  labels:
    app.kubernetes.io/name: translator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  customerCA.crt: {{ required "A valid .Values.hsm.customerCA entry required!" .Values.hsm.customerCA | quote }}
