apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-vmc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vmc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
