apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vmc
  labels:
    app.kubernetes.io/name: vmc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  customerCA.crt: {{ required "A valid .Values.hsm.customerCA required!" .Values.hsm.customerCA | quote }}
  hsm_signing_cert.pem: {{ required "A valid .Values.vmc.signingCert required!" .Values.vmc.signingCert | quote }}
