FROM verifybuild/java8:latest
ENV LC_ALL     en_GB.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ADD local_eidas_reference/ida-stub-idp /ida-stub-idp
WORKDIR /ida-stub-idp
RUN apt-get update && apt-get install unzip
COPY local_eidas_reference/scripts/start-stub-idp.sh start-stub-idp.sh
COPY stub-idp/resources/local notification_resources
CMD "./start-stub-idp.sh"
