FROM verifybuild/java8:latest
ENV LC_ALL     en_GB.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ADD stub-idp /ida-stub-idp
ADD stub-idps.yml /ida-stub-idp/stub-idps.yml
WORKDIR /ida-stub-idp
CMD bin/stub-idp
