FROM verifybuild/java8:latest
ENV LC_ALL     en_GB.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ADD verify-eidas-proxy-node /verify-eidas-proxy-node
WORKDIR /verify-eidas-proxy-node
CMD bin/verify-eidas-proxy-node
