FROM verifybuild/java8:latest
ENV LC_ALL     en_GB.UTF-8
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ADD . /verify-eidas-notification
WORKDIR /verify-eidas-notification
RUN apt-get update && apt-get install unzip
CMD "local_eidas_reference/scripts/start-proxy-node.sh"
